apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "spring-sample", "namespace": "dev",
        "kind": "DeploymentConfig"}]'
    creationTimestamp: "2020-02-29T19:41:33Z"
    labels:
      name: myfirstpipeline
    name: myfirstpipeline
    namespace: cicd
    resourceVersion: "76998"
    selfLink: /apis/build.openshift.io/v1/namespaces/cicd/buildconfigs/myfirstpipeline
    uid: 7d3fc72b-5b2b-11ea-934f-0242ac11000f
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node() {
          stage 'build'
          openshiftBuild(namespace: 'dev', buildConfig: 'spring-sample', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(namespace: 'dev',deploymentConfig: 'spring-sample')
          openshiftScale(namespace: 'dev',deploymentConfig: 'spring-sample',replicaCount: '3')
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
