apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "spring-sample", "namespace": "",
      "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: springpipeline
  name: springpipeline
  selfLink: /apis/build.openshift.io/v1/namespaces/cicd/buildconfigs/springpipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node() {\nstage 'build-dev'\n    openshiftBuild(namespace: 'dev',
        buildConfig: 'spring-sample', showBuildLogs: 'true')\nstage 'deploy-dev'\n
        \   openshiftDeploy(namespace: 'dev',deploymentConfig: 'spring-sample')\n
        \   openshiftScale(namespace: 'dev',deploymentConfig: 'spring-sample',replicaCount:
        '1')\n\nstage 'deploy-stage'\n    openshiftTag(namespace: 'dev', sourceStream:
        'spring-sample',  sourceTag: 'latest', destinationStream: 'spring-sample',
        destinationTag: 'promoteToQA')\n\n    openshiftDeploy(namespace: 'stage',deploymentConfig:
        'spring-sample')\n    openshiftScale(namespace: 'stage',deploymentConfig:
        'spring-sample',replicaCount: '1')\n    \n}"
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
